apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: sac
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: timescale/timescaledb:latest-pg17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sac
            - name: POSTGRES_USER
              value: sac
            - name: POSTGRES_PASSWORD
              value: sac-quickstart-pass
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sac
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
